<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="68898" started-at="2018-01-19T15:12:10Z" finished-at="2018-01-19T15:13:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="68898" started-at="2018-01-19T15:12:10Z" finished-at="2018-01-19T15:13:18Z">
      <class name="testcases.TC_005">
        <test-method status="PASS" signature="setValues()[pri:0, instance:testcases.TC_005@543c6f6d]" name="setValues" is-config="true" duration-ms="17" started-at="2018-01-19T20:42:10Z" finished-at="2018-01-19T20:42:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setValues -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.TC_005@543c6f6d]" name="beforeMethod" is-config="true" duration-ms="15498" started-at="2018-01-19T20:42:10Z" finished-at="2018-01-19T20:42:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login(java.lang.String, java.lang.String)[pri:0, instance:testcases.TC_005@543c6f6d]" name="login" duration-ms="51053" started-at="2018-01-19T20:42:26Z" data-provider="fetchData" finished-at="2018-01-19T20:43:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[836524978]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[@09safepass]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[lists don't have the same size expected [9] but found [10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: lists don't have the same size expected [9] but found [10]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:652)at org.testng.Assert.assertEquals(Assert.java:819)at org.testng.Assert.assertEquals(Assert.java:796)at generics.TestBase.compareBeneficiarys(TestBase.java:120)at pages.TransferFunds.verifyListOfBeneficiars(TransferFunds.java:159)at testcases.TC_005.login(TC_005.java:33)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.TC_005@543c6f6d]" name="afterMethod" is-config="true" duration-ms="1399" started-at="2018-01-19T20:43:17Z" finished-at="2018-01-19T20:43:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testcases.TC_005 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
